name: CI Testing

on:
  push:
    branches: 
      - develop
      - feature/tests
  pull_request:
    branches:
      - develop

jobs:
  test-users:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Run tests with Jest
      run: npm test